
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[window.padding]
x = 20
y = 20

[general]
import = [ "/home/rentatsu/.config/alacritty/themes/tokyo-night.toml" ]
